### ISSUE TITLE
Blah-code is not working anymore

### ISSUE THREAD

**Issue by LukyVj** [bullgit/blah-code#14]
On the client side : https://bullg.it/blah-code/ the online tool doesn't work anymore. 
`Uncaught ReferenceError: blahCode is not defined`

**Comment by Haroenv** [comment]
cdn.rawgit.com is down

**Comment by mischah** [comment]
What the actual fuck.

https://cdn.rawgit.com/bullgit/blah-code/2.0.1/blah-code.min.js returns with:

> 500 Internal Server Error
> 
> Shit.

But https://rawgit.com/ is up and running.

**Comment by mischah** [comment]
Ok. Seems to be a known issue:
https://twitter.com/rawgit/status/710846374737108992

**Comment by mischah** [comment]
cdn is back
