### ISSUE TITLE
Live updating

### ISSUE THREAD

**Issue by Haroenv** [bullgit/blah-code#7]
I'll quote @ArnaudWeyts

> Waarom is da niet live-updating zo da je niet op de knop moet drukken?

translation

> Why isn't this live-updating (i.e. convert on `input.addEventListener('input')` instead of `buttonaddEventListener('click')`?

**Comment by mischah** [comment]
Thats a good question. or better use `input.addEventListener('change)`?

I would give it a try if no one is faster with creating a PR 😜

**Comment by Haroenv** [comment]
Yep, you were slower, my PR seems to work @mischah

**Comment by mischah** [comment]
:rocket: :+1: 

Check my comment in the PR
